# Process Hazraty-Kari *et al.*, Persian Gulf Disease Data

This manuscript dataset has total numbers of corals for each genus, and the percentage of those taht had each of 6 categories of disease. This script converts the raw data from the manuscript into Tidy format (e.g. filling in genus name in each row), and combines the total counts with the percentage disease to infer counts of healthy vs. diseased corals.

## Import data as a pandas DataFrame

In [57]:
from os import listdir
listdir( "../Raw_Data")

['.DS_Store',
 'GLTMP_corals_2010-2019.csv',
 'Hazraty-Kari_et_al.csv',
 '.ipynb_checkpoints']

In [58]:
import pandas as pd
Persian_gulf = pd.read_csv("../Raw_Data/Hazraty-Kari_et_al.csv", keep_default_na=False, skiprows=[0])
Persian_gulf

,Genus,year,n,Rel. Abundance (%),BBD,SGA,WMD,AYBD,WS,PPS
0,Acropora,2014,486,21.86,2.71 ± 0.7,0,0,0,0.95 ± 0.6,0
1,,2015,379,12.61,0.78 ± 0.78,0.45 ± 0.27,0,0,4.23 ± 1.33,0
2,Porites,2014,659,29.64,0,0,3.53 ± 2.23,0.52 ± 0.52,0,4.96 ± 2.91
3,,2015,405,13.47,0,0.23 ± 0.17,1.3 ± 0.59,0,0,0.62 ± 0.39
4,Cyphastrea,2014,56,2.52,0,0,0,0,0,0
5,,2015,101,3.36,0,0,4.68 ± 3.44,0,0,0
6,Platygyra,2014,308,13.86,0,0,0,0,0,0
7,,2015,379,12.61,0,0.78 ± 0.78,0,0,0,0
8,Favites,2014,312,14.04,0,0,2.48 ± 0.9,0,0,0
9,,2015,344,11.44,0,0,5.12 ± 1.85,0,0,0
10,Dipsastrea,2014,252,11.34,0,0,0,0,0,0
11,,2015,700,23.29,0,0,1.46 ± 0.63,0,0,0
12,Conscinaraea,2014,88,3.96,0,0,1.46 ± 0.65,0.45 ± 0.33,0,0
13,,2015,228,7.58,0,0,0.2 ± 0.14,1.77 ± 0.54,0,0
14,Leptastrea,2014,60,2.70,0,0,0,0,0,0
15,,2015,111,3.69,0,0,0.96 ± 0.67,0,0,0

## Infer missing genus labels

Next, we'll infer missing genus labels from those in previous rows, and add them to the DataFrame

In [59]:
for index, row in Persian_gulf.iterrows():
    if not row['Genus']:
        row['Genus'] = current_genus
        Persian_gulf.at[index,'Genus'] = current_genus
    current_genus = row['Genus']
    print(current_genus)

Acropora
Acropora
Porites
Porites
Cyphastrea
Cyphastrea
Platygyra
Platygyra
Favites
Favites
Dipsastrea
Dipsastrea
Conscinaraea
Conscinaraea
Leptastrea
Leptastrea

In [60]:
Persian_gulf

,Genus,year,n,Rel. Abundance (%),BBD,SGA,WMD,AYBD,WS,PPS
0,Acropora,2014,486,21.86,2.71 ± 0.7,0,0,0,0.95 ± 0.6,0
1,Acropora,2015,379,12.61,0.78 ± 0.78,0.45 ± 0.27,0,0,4.23 ± 1.33,0
2,Porites,2014,659,29.64,0,0,3.53 ± 2.23,0.52 ± 0.52,0,4.96 ± 2.91
3,Porites,2015,405,13.47,0,0.23 ± 0.17,1.3 ± 0.59,0,0,0.62 ± 0.39
4,Cyphastrea,2014,56,2.52,0,0,0,0,0,0
5,Cyphastrea,2015,101,3.36,0,0,4.68 ± 3.44,0,0,0
6,Platygyra,2014,308,13.86,0,0,0,0,0,0
7,Platygyra,2015,379,12.61,0,0.78 ± 0.78,0,0,0,0
8,Favites,2014,312,14.04,0,0,2.48 ± 0.9,0,0,0
9,Favites,2015,344,11.44,0,0,5.12 ± 1.85,0,0,0
10,Dipsastrea,2014,252,11.34,0,0,0,0,0,0
11,Dipsastrea,2015,700,23.29,0,0,1.46 ± 0.63,0,0,0
12,Conscinaraea,2014,88,3.96,0,0,1.46 ± 0.65,0.45 ± 0.33,0,0
13,Conscinaraea,2015,228,7.58,0,0,0.2 ± 0.14,1.77 ± 0.54,0,0
14,Leptastrea,2014,60,2.70,0,0,0,0,0,0
15,Leptastrea,2015,111,3.69,0,0,0.96 ± 0.67,0,0,0

## Split columns that have ± values

We want mean and standard deviation values in separate columns so we can multiply the percent disease value by the number of corals. So we'll next separate out those values.

In [61]:
import pandas as pd
Persian_gulf = pd.read_csv("../Raw_Data/Hazraty-Kari_et_al.csv", keep_default_na=False, skiprows=[0])

#Adding in missing genus names 
for index, row in Persian_gulf.iterrows():
    if not row['Genus']:
        row['Genus'] = current_genus
        Persian_gulf.at[index,'Genus'] = current_genus
    current_genus = row['Genus']
    
#Dealing with columns that have ± and are 0s 
print("Columns in the DataFrame:",Persian_gulf.columns)
columns_to_split = ['BBD', 'SGA', 'WMD', 'AYBD', 'WS', 'PPS']

def split_value(value):
    return pd.Series(value.split("±", 1))

def split_column_of_values(col):
    col = list(col)
    number_col_data = []
    SD_col_data = []
    for entry in col:
        if entry == "0":
            entry = "0 ± 0"
        try:
            number, SD = entry.split("±")
        except ValueError:
            raise ValueError(f"entry {entry} doesn't split neatly. Does it not have a ±?")
        number = float(number)
        number = number/100
        number_col_data.append(number)
        SD_col_data.append(SD)
    return number_col_data,SD_col_data

for col in Persian_gulf.columns:
    if col not in columns_to_split:
        continue
        
    percent_col_data, sd_col_data = split_column_of_values(Persian_gulf[col])
    
    Persian_gulf[f"{col}_percent"] = percent_col_data
    Persian_gulf[f"{col}_SD"] = sd_col_data

Columns in the DataFrame: Index(['Genus', 'year', 'n ', 'Rel. Abundance (%)', 'BBD', 'SGA', 'WMD',
       'AYBD', 'WS', 'PPS'],
      dtype='object')

In [62]:
Persian_gulf

,Genus,year,n,Rel. Abundance (%),BBD,SGA,WMD,AYBD,WS,PPS,...,SGA_percent,SGA_SD,WMD_percent,WMD_SD,AYBD_percent,AYBD_SD,WS_percent,WS_SD,PPS_percent,PPS_SD
0,Acropora,2014,486,21.86,2.71 ± 0.7,0,0,0,0.95 ± 0.6,0,...,0.0000,0,0.0000,0,0.0000,0,0.0095,0.6,0.0000,0
1,Acropora,2015,379,12.61,0.78 ± 0.78,0.45 ± 0.27,0,0,4.23 ± 1.33,0,...,0.0045,0.27,0.0000,0,0.0000,0,0.0423,1.33,0.0000,0
2,Porites,2014,659,29.64,0,0,3.53 ± 2.23,0.52 ± 0.52,0,4.96 ± 2.91,...,0.0000,0,0.0353,2.23,0.0052,0.52,0.0000,0,0.0496,2.91
3,Porites,2015,405,13.47,0,0.23 ± 0.17,1.3 ± 0.59,0,0,0.62 ± 0.39,...,0.0023,0.17,0.0130,0.59,0.0000,0,0.0000,0,0.0062,0.39
4,Cyphastrea,2014,56,2.52,0,0,0,0,0,0,...,0.0000,0,0.0000,0,0.0000,0,0.0000,0,0.0000,0
5,Cyphastrea,2015,101,3.36,0,0,4.68 ± 3.44,0,0,0,...,0.0000,0,0.0468,3.44,0.0000,0,0.0000,0,0.0000,0
6,Platygyra,2014,308,13.86,0,0,0,0,0,0,...,0.0000,0,0.0000,0,0.0000,0,0.0000,0,0.0000,0
7,Platygyra,2015,379,12.61,0,0.78 ± 0.78,0,0,0,0,...,0.0078,0.78,0.0000,0,0.0000,0,0.0000,0,0.0000,0
8,Favites,2014,312,14.04,0,0,2.48 ± 0.9,0,0,0,...,0.0000,0,0.0248,0.9,0.0000,0,0.0000,0,0.0000,0
9,Favites,2015,344,11.44,0,0,5.12 ± 1.85,0,0,0,...,0.0000,0,0.0512,1.85,0.0000,0,0.0000,0,0.0000,0
10,Dipsastrea,2014,252,11.34,0,0,0,0,0,0,...,0.0000,0,0.0000,0,0.0000,0,0.0000,0,0.0000,0
11,Dipsastrea,2015,700,23.29,0,0,1.46 ± 0.63,0,0,0,...,0.0000,0,0.0146,0.63,0.0000,0,0.0000,0,0.0000,0
12,Conscinaraea,2014,88,3.96,0,0,1.46 ± 0.65,0.45 ± 0.33,0,0,...,0.0000,0,0.0146,0.65,0.0045,0.33,0.0000,0,0.0000,0
13,Conscinaraea,2015,228,7.58,0,0,0.2 ± 0.14,1.77 ± 0.54,0,0,...,0.0000,0,0.0020,0.14,0.0177,0.54,0.0000,0,0.0000,0
14,Leptastrea,2014,60,2.70,0,0,0,0,0,0,...,0.0000,0,0.0000,0,0.0000,0,0.0000,0,0.0000,0
15,Leptastrea,2015,111,3.69,0,0,0.96 ± 0.67,0,0,0,...,0.0000,0,0.0096,0.67,0.0000,0,0.0000,0,0.0000,0

In [73]:
Persian_gulf['healthy_count'] = Persian_gulf["n "]
Persian_gulf['total_diseased_count'] = 0 
for column_name in Persian_gulf.columns: 
    print(column_name)
    if column_name.endswith('_percent'):
        last_letter_index = len('_percent')*-1
        count_column_name = column_name[:last_letter_index]
        count_column_name = count_column_name + '_count'
        Persian_gulf[count_column_name] = Persian_gulf[column_name]*Persian_gulf["n "]
        Persian_gulf[count_column_name] = Persian_gulf[count_column_name].round()
        Persian_gulf[count_column_name] = Persian_gulf[count_column_name].astype(int)
        #Subtracting given counts of current disease from healthy count columns, assuming no corals have 2 diseases
        Persian_gulf['healthy_count'] -= Persian_gulf[count_column_name]
        Persian_gulf['total_diseased_count'] += Persian_gulf[count_column_name]

Genus
year
n
Rel. Abundance (%)
BBD
SGA
WMD
AYBD
WS
PPS
BBD_percent
BBD_SD
SGA_percent
SGA_SD
WMD_percent
WMD_SD
AYBD_percent
AYBD_SD
WS_percent
WS_SD
PPS_percent
PPS_SD
BBD_count
SGA_count
WMD_count
AYBD_count
WS_count
PPS_count
healthy_count
total_diseased_count

In [75]:
list(Persian_gulf.columns)

['Genus',
 'year',
 'n ',
 'Rel. Abundance (%)',
 'BBD',
 'SGA',
 'WMD',
 'AYBD',
 'WS',
 'PPS',
 'BBD_percent',
 'BBD_SD',
 'SGA_percent',
 'SGA_SD',
 'WMD_percent',
 'WMD_SD',
 'AYBD_percent',
 'AYBD_SD',
 'WS_percent',
 'WS_SD',
 'PPS_percent',
 'PPS_SD',
 'BBD_count',
 'SGA_count',
 'WMD_count',
 'AYBD_count',
 'WS_count',
 'PPS_count',
 'healthy_count',
 'total_diseased_count']

In [76]:
final_column_names = ['Genus', 'year', 'BBD_count','SGA_count','WMD_count','AYBD_count','WS_count','PPS_count','healthy_count','total_diseased_count']
final_table = Persian_gulf.loc[:,final_column_names]
final_table['n'] = Persian_gulf['n ']
final_table.to_csv("../Processed_Data/Persian_gulf_Hazraty-Kari_et_al.csv")