In [1]:
import pandas as pd
Persian_gulf = pd.read_csv("../Raw_Data/Sanaz_Hazraty-Kari_et_al.csv", keep_default_na=False, skiprows=[0])
Persian_gulf

,Genus,year,n,Rel. Abundance (%),BBD,SGA,WMD,AYBD,WS,PPS
0,Acropora,2014,486,21.86,2.71 ± 0.7,0,0,0,0.95 ± 0.6,0
1,,2015,379,12.61,0.78 ± 0.78,0.45 ± 0.27,0,0,4.23 ± 1.33,0
2,Porites,2014,659,29.64,0,0,3.53 ± 2.23,0.52 ± 0.52,0,4.96 ± 2.91
3,,2015,405,13.47,0,0.23 ± 0.17,1.3 ± 0.59,0,0,0.62 ± 0.39
4,Cyphastrea,2014,56,2.52,0,0,0,0,0,0
5,,2015,101,3.36,0,0,4.68 ± 3.44,0,0,0
6,Platygyra,2014,308,13.86,0,0,0,0,0,0
7,,2015,379,12.61,0,0.78 ± 0.78,0,0,0,0
8,Favites,2014,312,14.04,0,0,2.48 ± 0.9,0,0,0
9,,2015,344,11.44,0,0,5.12 ± 1.85,0,0,0
10,Dipsastrea,2014,252,11.34,0,0,0,0,0,0
11,,2015,700,23.29,0,0,1.46 ± 0.63,0,0,0
12,Conscinaraea,2014,88,3.96,0,0,1.46 ± 0.65,0.45 ± 0.33,0,0
13,,2015,228,7.58,0,0,0.2 ± 0.14,1.77 ± 0.54,0,0
14,Leptastrea,2014,60,2.70,0,0,0,0,0,0
15,,2015,111,3.69,0,0,0.96 ± 0.67,0,0,0

In [2]:
for index, row in Persian_gulf.iterrows():
    if not row['Genus']:
        row['Genus'] = current_genus
        Persian_gulf.at[index,'Genus'] = current_genus
    current_genus = row['Genus']
    print(current_genus)

Acropora
Acropora
Porites
Porites
Cyphastrea
Cyphastrea
Platygyra
Platygyra
Favites
Favites
Dipsastrea
Dipsastrea
Conscinaraea
Conscinaraea
Leptastrea
Leptastrea

In [3]:
Persian_gulf

,Genus,year,n,Rel. Abundance (%),BBD,SGA,WMD,AYBD,WS,PPS
0,Acropora,2014,486,21.86,2.71 ± 0.7,0,0,0,0.95 ± 0.6,0
1,Acropora,2015,379,12.61,0.78 ± 0.78,0.45 ± 0.27,0,0,4.23 ± 1.33,0
2,Porites,2014,659,29.64,0,0,3.53 ± 2.23,0.52 ± 0.52,0,4.96 ± 2.91
3,Porites,2015,405,13.47,0,0.23 ± 0.17,1.3 ± 0.59,0,0,0.62 ± 0.39
4,Cyphastrea,2014,56,2.52,0,0,0,0,0,0
5,Cyphastrea,2015,101,3.36,0,0,4.68 ± 3.44,0,0,0
6,Platygyra,2014,308,13.86,0,0,0,0,0,0
7,Platygyra,2015,379,12.61,0,0.78 ± 0.78,0,0,0,0
8,Favites,2014,312,14.04,0,0,2.48 ± 0.9,0,0,0
9,Favites,2015,344,11.44,0,0,5.12 ± 1.85,0,0,0
10,Dipsastrea,2014,252,11.34,0,0,0,0,0,0
11,Dipsastrea,2015,700,23.29,0,0,1.46 ± 0.63,0,0,0
12,Conscinaraea,2014,88,3.96,0,0,1.46 ± 0.65,0.45 ± 0.33,0,0
13,Conscinaraea,2015,228,7.58,0,0,0.2 ± 0.14,1.77 ± 0.54,0,0
14,Leptastrea,2014,60,2.70,0,0,0,0,0,0
15,Leptastrea,2015,111,3.69,0,0,0.96 ± 0.67,0,0,0

In [14]:
import pandas as pd
Persian_gulf = pd.read_csv("../Raw_Data/Sanaz_Hazraty-Kari_et_al.csv", keep_default_na=False, skiprows=[0])
#Adding in missing genus names 
for index, row in Persian_gulf.iterrows():
    if not row['Genus']:
        row['Genus'] = current_genus
        Persian_gulf.at[index,'Genus'] = current_genus
    current_genus = row['Genus']
    
#Dealing with columns that have ± and are 0s 
columns_to_split = ['BBD', 'SGA', 'WMD', 'AYBD', 'WS', 'PPS']

def split_value(value):
    return pd.Series(value.split("±", 1))

for col in Persian_gulf.columns:
    print(col)
    if col not in columns_to_split:
        continue
    print(col)
    new_column_name = col + "_split"
    Persian_gulf[Persian_gulf[col]== "0"] = "0 ± 0"
    #Persian_gulf[col] = Persian_gulf[col].str.replace("0", "0±0", regex=False)
    print(Persian_gulf[col])
    Persian_gulf[[f"{col}_percent"], Persian_gulf[f"{col}_SD"]] = Persian_gulf[col].apply(split_value)
    #Persian_gulf[f"{col}_percent"], Persian_gulf[f"{col}_SD"] = Persian_gulf[col].str.split('±', n=1, expand=False)
    print(f"After splitting {col}:")
    #print(Persian_gulf[[col, new_column_name]])

Genus
year
n
Rel. Abundance (%)
BBD
BBD
0      2.71 ± 0.7
1     0.78 ± 0.78
2           0 ± 0
3           0 ± 0
4           0 ± 0
5           0 ± 0
6           0 ± 0
7           0 ± 0
8           0 ± 0
9           0 ± 0
10          0 ± 0
11          0 ± 0
12          0 ± 0
13          0 ± 0
14          0 ± 0
15          0 ± 0
Name: BBD, dtype: object

KeyError: 'BBD_SD'

In [10]:
Persian_gulf

,Genus,year,n,Rel. Abundance (%),BBD,SGA,WMD,AYBD,WS,PPS,...,SGA_percent,SGA_SD,WMD_percent,WMD_SD,AYBD_percent,AYBD_SD,WS_percent,WS_SD,PPS_percent,PPS_SD
0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,...,0,1,0,1,0,1,0,1,0,1
1,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,...,0 ± 0,0 ± 0,0,1,0,1,0,1,0,1
2,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,...,0,1,0,1,0,1,0,1,0,1
3,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,...,0,1,0,1,0,1,0,1,0,1
4,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,...,0,1,0,1,0,1,0,1,0,1
5,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,...,0,1,0,1,0,1,0,1,0,1
6,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,...,0,1,0,1,0,1,0,1,0,1
7,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,...,0,1,0,1,0,1,0,1,0,1
8,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,...,0,1,0,1,0,1,0,1,0,1
9,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,...,0,1,0,1,0,1,0,1,0,1
10,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,...,0,1,0,1,0,1,0,1,0,1
11,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,...,0,1,0,1,0,1,0,1,0,1
12,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,...,0,1,0,1,0,1,0,1,0,1
13,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,...,0,1,0,1,0,1,0,1,0,1
14,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,...,0,1,0,1,0,1,0,1,0,1
15,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,0 ± 0,...,0,1,0,1,0,1,0,1,0,1